services:
  - type: web
    name: portfolio-686f6c61
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve dist -l 10000
    envVars:
      - key: NODE_VERSION
        value: 18
